title: NIC Nepal
email: nicnepal.mahabir@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  It is a non-profit organisation and is incorporated on the 9th day of November, 2012 pursuant to sub-section (1) of section 5 of the Companies Act, 2006. 
  Its registered address is at Shivabhakta Marg, 304, Lazimpat, Kathmandu Nepal. NIC Research and Development facility is located at Kirtipur, Kathmandu in the premises of Tribhuwan University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-133657720-2

include: ['_projects']

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
