title: Agency Starter Template
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a starter template for Agency theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# change the default sass folder

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
